# Generated by Django 2.1.1 on 2018-10-13 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='text',
            name='number',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
